platform :ios,'8.0'
use_frameworks!

target 'OC_Extend_Example' do
  pod 'OC_Extend', :path => '../'
# pod 'OC_Extend'
  pod 'GBDeviceInfo'
  pod 'YYCache', '~> 1.0.4'
  
  target 'OC_Extend_Tests' do
    inherit! :search_paths

    
  end
end
